"""
Function File: pressure_distribution.py
------------------------
What it does:
    - Computes the pressure field around the airfoil using the velocity field
      obtained from thin airfoil theory.
    - Uses the velocity components generated by the vortex sheet formulation
      implemented in velocity_vector_field.py.
    - Applies Bernoulli’s equation to compute static pressure at each point
      in the computational grid.
    - Generates a pressure distribution visualization around the airfoil
      using filled contour plots.
    - Displays the rotated camber line corresponding to the airfoil orientation
      at the specified angle of attack.

Theory Used:
    - Thin Airfoil Theory to obtain the vortex sheet circulation distribution.
    - Biot–Savart Law to compute velocity induced by vortex elements.
    - Superposition principle combining freestream velocity and induced velocity.
    - Bernoulli's equation for incompressible inviscid flow to relate velocity
      magnitude and pressure.

Bernoulli Equation Used:

        p + (1/2)ρV² = p∞ + (1/2)ρU∞²

    Rearranged for pressure:

        p = p∞ + (1/2)ρ(U∞² − V²)

Inputs (from user_input and dependent modules):
    - m : Maximum camber of the airfoil (fraction of chord)
    - p : Position of maximum camber (fraction of chord)
    - input_type : Specifies NACA camber line (1) or user-defined camber (2)
    - user_defined_camber : Function defining the camber line if user-defined
      option is selected
    - alpha_deg : Angle of attack in degrees

Other variables:
    - X, Y : Meshgrid defining the computational grid around the airfoil
    - U, V : Velocity components at each grid point
    - speed : Magnitude of velocity at each grid point
    - pressure : Static pressure computed at each grid point
    - x_rot, z_rot : Camber line coordinates rotated to represent the airfoil
      at the specified angle of attack

Functions:
    - pressure_distribution : Computes pressure values across the grid.
    - pressure_plot : Generates and saves a pressure contour visualization.

Outputs:
    - Pressure_distribution.png : Contour plot showing pressure field
      around the airfoil.

Assumptions:
    - Airfoil chord is normalized from x = 0 (leading edge) to x = 1 (trailing edge)
    - Thin airfoil theory assumptions apply (small camber and small angle of attack)
    - Flow is incompressible and inviscid
    - Bernoulli's equation holds throughout the flow field
    - Pressure is computed using the velocity field obtained from the vortex
      sheet representation of the airfoil
"""

import numpy as np
import matplotlib.pyplot as plt

from velocity_vector_field import velocity_field
from velocity_vector_field import X, Y, x_rot, z_rot


def pressure_distribution(U_inf=20, rho=1.225, p_inf=101325):
    """
    Computes pressure distribution across the computational grid.
    """
    U, V = velocity_field(U_inf)

    # Velocity magnitude
    speed = np.sqrt(U**2 + V**2)

    # Bernoulli equation
    pressure = p_inf + 0.5 * rho * (U_inf**2 - speed**2)

    return pressure


def pressure_plot(U_inf=20, rho=1.225, p_inf=101325):
    """
    Generates a pressure contour plot around the airfoil.
    """

    pressure = pressure_distribution(U_inf, rho, p_inf)

    plt.figure(figsize=(12, 8))

    contour = plt.contourf(
        X,
        Y,
        pressure,
        levels=1000,
        cmap="jet"
    )

    plt.colorbar(contour, label="Pressure (Pa)")

    # Plot camber line of airfoil
    plt.plot(x_rot, z_rot, color='black', linewidth=2, label="Camber Line")

    plt.xlim(-1, 3)
    plt.ylim(-1.5, 1.5)

    plt.xlabel("x (in meters)")
    plt.ylabel("y (in meters)")

    plt.title("Pressure Distribution Around the Airfoil")

    plt.legend()
    plt.axis("equal")

    plt.savefig("Pressure_distribution.png", dpi=300)

    plt.show()


if __name__ == "__main__":
    pressure_plot()
